# Generated by Django 3.2.7 on 2021-10-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='proble',
            new_name='problem',
        ),
    ]
