# Generated by Django 3.2.7 on 2021-10-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_proble_picture_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='athor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='proble',
            new_name='problem',
        ),
    ]
